/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as ManufacturingRouteImport } from './routes/manufacturing'
import { Route as FlavoursRouteImport } from './routes/flavours'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturingRoute = ManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavoursRoute = FlavoursRouteImport.update({
  id: '/flavours',
  path: '/flavours',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/flavours': typeof FlavoursRoute
  '/manufacturing': typeof ManufacturingRoute
  '/our-story': typeof OurStoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/flavours': typeof FlavoursRoute
  '/manufacturing': typeof ManufacturingRoute
  '/our-story': typeof OurStoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/flavours': typeof FlavoursRoute
  '/manufacturing': typeof ManufacturingRoute
  '/our-story': typeof OurStoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/flavours' | '/manufacturing' | '/our-story'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/flavours' | '/manufacturing' | '/our-story'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/flavours'
    | '/manufacturing'
    | '/our-story'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FlavoursRoute: typeof FlavoursRoute
  ManufacturingRoute: typeof ManufacturingRoute
  OurStoryRoute: typeof OurStoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturing': {
      id: '/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof ManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavours': {
      id: '/flavours'
      path: '/flavours'
      fullPath: '/flavours'
      preLoaderRoute: typeof FlavoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FlavoursRoute: FlavoursRoute,
  ManufacturingRoute: ManufacturingRoute,
  OurStoryRoute: OurStoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
